In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Loading Data

In [56]:
# Load data

providers = pd.read_csv('/Users/anupamverma/Downloads/providers_data.csv')
receivers = pd.read_csv('/Users/anupamverma/Downloads/receivers_data.csv')
food_listings = pd.read_csv('/Users/anupamverma/Downloads/food_listings_data.csv')
claims = pd.read_csv('/Users/anupamverma/Downloads/claims_data.csv')

### Data Cleaning

In [29]:
providers

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577
...,...,...,...,...,...,...
995,996,"Vasquez, Ruiz and Flowers",Restaurant,"84308 Justin Stravenue\nNew Amberside, NE 53447",Williamview,+1-319-378-7627x0682
996,997,Garza-Williams,Catering Service,"08864 Figueroa Radial Suite 948\nJennaberg, AZ...",East Rossside,001-924-441-3963x746
997,998,Novak Group,Grocery Store,"934 Zachary Run\nMelissamouth, WY 02729",Joshuastad,(903)642-1969x3300
998,999,Moody Ltd,Grocery Store,"17580 Ernest Hills\nLake Michaelmouth, OR 56416",Stevenchester,637.300.3664x4880
999,1000,Jenkins-Brooks,Restaurant,"53390 Evans Rapids Suite 982\nLake Meghan, MO ...",Brendantown,266-324-3458x95775

In [30]:
# Checking Type and Null Values
providers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   str
 2   Type         1000 non-null   str
 3   Address      1000 non-null   str
 4   City         1000 non-null   str
 5   Contact      1000 non-null   str
dtypes: int64(1), str(5)
memory usage: 145.6 KB

In [57]:
# Data Cleaning
# 1. Clean up newline characters in Address
providers['Address'] = providers['Address'].str.replace('\n', ', ', regex=False)

# 2. Extract extension from contact if present
providers['P_Extension'] = providers['Contact'].str.extract(r'x(\d+)')
# Strip extensions and special characters from contact numbers to clean them
providers['P_Clean_Contact'] = providers['Contact'].str.replace(r'x\d+', '', regex=True).str.replace(r'[\s\-\(\)\.]', '', regex=True)

providers.head()

,Provider_ID,Name,Type,Address,City,Contact,P_Extension,P_Clean_Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions, Andreamouth, OK ...",New Jessica,+1-600-220-0480,NaN,+16002200480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream, Welchtown, OR 27136",East Sheena,+1-925-283-8901x6297,6297,+19252838901
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507, Guzmanchester, W...",Lake Jesusview,001-517-295-2206,NaN,0015172952206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409, Port Jesus, IA 61188",Mendezmouth,556.944.8935x401,401,5569448935
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319, Saraborough, MA 53978",Valentineside,193.714.6577,NaN,1937146577

In [32]:
# Check For Unique Values
providers.nunique()

Provider_ID        1000
Name                973
Type                  4
Address            1000
City                963
Contact            1000
P_Extension         584
P_Clean_Contact    1000
dtype: int64

In [33]:
receivers.sample(10)

,Receiver_ID,Name,Type,City,Contact
71,72,Charles Davidson,Shelter,West Angelatown,+1-294-698-2957
38,39,John Ramirez,Shelter,Moorechester,(859)701-8773
224,225,Joseph Bowman,NGO,West Jessica,001-363-434-2847x24463
451,452,Tina Banks,Charity,Port Judith,986-535-7620
615,616,Christopher Wright,Shelter,New Kellytown,+1-631-074-8622x827
81,82,Laura Bennett,NGO,Evansside,(379)719-1693x40160
600,601,Peter Gonzalez,Shelter,Biancaton,(112)578-4601x9811
130,131,Shawn Mills,Charity,Jeffhaven,+1-951-192-1790
186,187,Amy Thomas,Shelter,Lake Erica,+1-215-295-0597x4795
63,64,Debra Sheppard,Shelter,North Darinshire,001-726-678-1689

In [34]:
# Check for Type and Null values
receivers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Receiver_ID  1000 non-null   int64
 1   Name         1000 non-null   str
 2   Type         1000 non-null   str
 3   City         1000 non-null   str
 4   Contact      1000 non-null   str
dtypes: int64(1), str(4)
memory usage: 86.1 KB

In [58]:
# Data Cleaning
# Extract extension from contact if present
receivers['R_Extension'] = receivers['Contact'].str.extract(r'x(\d+)')
# Strip extensions and special characters from contact numbers to clean them
receivers['R_Clean_Contact'] = receivers['Contact'].str.replace(r'x\d+', '', regex=True).str.replace(r'[\s\-\(\)\.]', '', regex=True)

In [36]:
receivers.sample(10)

,Receiver_ID,Name,Type,City,Contact,R_Extension,R_Clean_Contact
236,237,Cathy Adams,Shelter,West Josephshire,269-061-4726,NaN,2690614726
230,231,Christopher Barrett,Charity,Port Brianville,+1-099-740-1254x66035,66035,+10997401254
610,611,Jeff Rivas,Charity,Mcdanielmouth,675.065.4290x4573,4573,6750654290
116,117,Kelly Pierce,Shelter,East Heatherborough,517.232.1717,NaN,5172321717
24,25,Lisa Mcclain,NGO,Lake Elizabeth,292-153-9082x59361,59361,2921539082
74,75,Nicholas Smith,Charity,Manningtown,+1-605-970-1115,NaN,+16059701115
131,132,Katherine Gomez,Charity,South Jasonberg,(609)802-2108x3673,3673,6098022108
664,665,Felicia Collier,NGO,Toddstad,+1-113-202-4089x101,101,+11132024089
205,206,Ashley Brooks,Individual,Ramseystad,428.820.9314,NaN,4288209314
124,125,Tammy Smith,Individual,Campbellchester,001-668-537-1925x410,410,0016685371925

In [37]:
food_listings.sample(10)

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
79,80,Dairy,36,3/29/2025,434,Restaurant,Nicoletown,Vegetarian,Breakfast
519,520,Fish,23,3/25/2025,559,Catering Service,New Baileyfort,Non-Vegetarian,Breakfast
812,813,Fish,33,3/23/2025,610,Supermarket,Allenton,Vegetarian,Breakfast
629,630,Bread,39,3/25/2025,478,Catering Service,Lake Regina,Vegan,Snacks
17,18,Soup,28,3/27/2025,455,Catering Service,Madisonfort,Vegan,Snacks
759,760,Dairy,28,3/26/2025,710,Catering Service,Mikaylachester,Non-Vegetarian,Dinner
450,451,Fish,14,3/18/2025,713,Grocery Store,Smithmouth,Vegan,Breakfast
38,39,Bread,48,3/22/2025,758,Catering Service,Port Patrick,Non-Vegetarian,Breakfast
445,446,Bread,9,3/24/2025,39,Supermarket,Brittanyville,Non-Vegetarian,Snacks
39,40,Fruits,12,3/27/2025,965,Restaurant,Port Bryce,Vegetarian,Breakfast

In [38]:
# Check for Type and Null values
food_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   str
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   str
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   str
 6   Location       1000 non-null   str
 7   Food_Type      1000 non-null   str
 8   Meal_Type      1000 non-null   str
dtypes: int64(3), str(6)
memory usage: 124.2 KB

In [59]:
# Converting Expiry_Date form str to datetime Type
food_listings['Expiry_Date'] = pd.to_datetime(food_listings['Expiry_Date'])

In [40]:
food_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   str
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   datetime64[us]
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   str
 6   Location       1000 non-null   str
 7   Food_Type      1000 non-null   str
 8   Meal_Type      1000 non-null   str
dtypes: datetime64[us](1), int64(3), str(5)
memory usage: 115.4 KB

In [41]:
claims.sample(10)

     Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
665       666      749          130    Pending   3/15/2025 9:02
572       573      229          505  Completed  3/12/2025 15:46
443       444      128          660  Cancelled   3/11/2025 3:57
281       282      161          298  Cancelled   3/14/2025 7:06
975       976      551          409  Completed   3/7/2025 12:50
442       443      879          124  Completed   3/5/2025 12:55
835       836      733          532    Pending   3/18/2025 0:13
390       391      807          950  Completed   3/4/2025 20:52
960       961      955          181  Completed   3/16/2025 5:05
56         57      225          295  Completed  3/11/2025 21:44

In [42]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   str
 4   Timestamp    1000 non-null   str
dtypes: int64(3), str(2)
memory usage: 61.2 KB

In [60]:
# Converting Timestamp form str to datetime Type
claims['Timestamp'] = pd.to_datetime(claims['Timestamp'])

In [44]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   str
 4   Timestamp    1000 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 47.3 KB

### Preparing for SQL Export

In [61]:
# Clean up categorical string columns across all tables for trailing Whitespaces
claims['Status'] = claims['Status'].str.strip()
food_listings['Food_Name'] = food_listings['Food_Name'].str.strip()
food_listings['Food_Type'] = food_listings['Food_Type'].str.strip()
food_listings['Meal_Type'] = food_listings['Meal_Type'].str.strip()
food_listings['Provider_Type'] = food_listings['Provider_Type'].str.strip()
providers['Type'] = providers['Type'].str.strip()
receivers['Type'] = receivers['Type'].str.strip()

In [62]:
# Drop Provider type because when we JOIN it in SQL with Provider ID No need for the Provider_type Column
food_listings = food_listings.drop(columns=['Provider_Type'])

In [63]:
food_listings

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Location,Food_Type,Meal_Type
0,1,Bread,43,2025-03-17,110,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,2025-03-24,791,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,2025-03-28,478,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,2025-03-16,930,Kellytown,Vegan,Lunch
4,5,Soup,14,2025-03-19,279,Garciaport,Vegan,Dinner
...,...,...,...,...,...,...,...,...
995,996,Fish,15,2025-03-30,467,Phillipsfort,Vegan,Breakfast
996,997,Fish,22,2025-03-18,35,Andersonmouth,Vegetarian,Breakfast
997,998,Fruits,6,2025-03-22,444,New Billy,Non-Vegetarian,Dinner
998,999,Pasta,15,2025-03-30,702,Lake Mistyton,Non-Vegetarian,Lunch
999,1000,Salad,18,2025-03-19,155,Charlesview,Non-Vegetarian,Dinner

In [66]:
receivers

,Receiver_ID,Name,Type,City,Contact_Number,R_Extension,R_Clean_Contact
0,1,Donald Gomez,Shelter,Port Carlburgh,(955)922-5295,NaN,9559225295
1,2,Laurie Ramos,Individual,Lewisburgh,761.042.1570,NaN,7610421570
2,3,Ashley Mckee,NGO,South Randalltown,691-023-0094x856,856,6910230094
3,4,Erika Rose,NGO,South Shaneville,8296491111,NaN,8296491111
4,5,John Romero,Individual,Bakerport,067.491.0154,NaN,0674910154
...,...,...,...,...,...,...,...
995,996,Matthew Curtis,Shelter,Lanechester,127-889-4442x1289,1289,1278894442
996,997,Amanda Cain,NGO,New Steven,+1-001-491-5601x5316,5316,+10014915601
997,998,Theodore Briggs,Individual,South Sandra,930-609-9442x5031,5031,9306099442
998,999,Cheyenne Ramsey,NGO,Lake Jeffery,001-326-320-4816x15300,15300,0013263204816
999,1000,April Miller,Shelter,Shelbychester,894-873-2652x23999,23999,8948732652

In [67]:
# Keep only the cleaned columns and rename them to final database names
providers = providers.drop(columns=['Contact_Number'])
providers = providers.rename(columns={'P_Clean_Contact': 'Contact_Number', 'P_Extension': 'Phone_Extension'})

receivers = receivers.drop(columns=['Contact_Number'])
receivers = receivers.rename(columns={'R_Clean_Contact': 'Contact_Number', 'R_Extension': 'Phone_Extension'})

In [68]:
providers

,Provider_ID,Name,Type,Address,City,Phone_Extension,Contact_Number
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions, Andreamouth, OK ...",New Jessica,NaN,+16002200480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream, Welchtown, OR 27136",East Sheena,6297,+19252838901
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507, Guzmanchester, W...",Lake Jesusview,NaN,0015172952206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409, Port Jesus, IA 61188",Mendezmouth,401,5569448935
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319, Saraborough, MA 53978",Valentineside,NaN,1937146577
...,...,...,...,...,...,...,...
995,996,"Vasquez, Ruiz and Flowers",Restaurant,"84308 Justin Stravenue, New Amberside, NE 53447",Williamview,0682,+13193787627
996,997,Garza-Williams,Catering Service,"08864 Figueroa Radial Suite 948, Jennaberg, AZ...",East Rossside,746,0019244413963
997,998,Novak Group,Grocery Store,"934 Zachary Run, Melissamouth, WY 02729",Joshuastad,3300,9036421969
998,999,Moody Ltd,Grocery Store,"17580 Ernest Hills, Lake Michaelmouth, OR 56416",Stevenchester,4880,6373003664
999,1000,Jenkins-Brooks,Restaurant,"53390 Evans Rapids Suite 982, Lake Meghan, MO ...",Brendantown,95775,2663243458

In [69]:
receivers

,Receiver_ID,Name,Type,City,Phone_Extension,Contact_Number
0,1,Donald Gomez,Shelter,Port Carlburgh,NaN,9559225295
1,2,Laurie Ramos,Individual,Lewisburgh,NaN,7610421570
2,3,Ashley Mckee,NGO,South Randalltown,856,6910230094
3,4,Erika Rose,NGO,South Shaneville,NaN,8296491111
4,5,John Romero,Individual,Bakerport,NaN,0674910154
...,...,...,...,...,...,...
995,996,Matthew Curtis,Shelter,Lanechester,1289,1278894442
996,997,Amanda Cain,NGO,New Steven,5316,+10014915601
997,998,Theodore Briggs,Individual,South Sandra,5031,9306099442
998,999,Cheyenne Ramsey,NGO,Lake Jeffery,15300,0013263204816
999,1000,April Miller,Shelter,Shelbychester,23999,8948732652

In [51]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.9.12)

In [70]:
from sqlalchemy import create_engine

# Define your PostgreSQL connection string
DATABASE_URL = "postgresql://postgres:@localhost:5432/food_wastage"

# Create the engine
engine = create_engine(DATABASE_URL)

# Export dataframes to PostgreSQL tables
providers.to_sql('providers', engine, if_exists='replace', index=False)
receivers.to_sql('receivers', engine, if_exists='replace', index=False)
food_listings.to_sql('food_listings', engine, if_exists='replace', index=False)
claims.to_sql('claims', engine, if_exists='replace', index=False)

print("All four tables have been successfully exported to PostgreSQL!")

All four tables have been successfully exported to PostgreSQL!

In [73]:
providers.to_csv('providers_cleaned.csv', index=False)

In [74]:
receivers.to_csv('recevers_cleaned.csv', index=False)
food_listings.to_csv('food_listings_cleaned.csv', index=False)
claims.to_csv('claims_cleaned.csv', index=False)

### Data Analysis and EDA

In [75]:
# Check shapes of all DataFrames
print(f"Providers: {providers.shape}")
print(f"Receivers: {receivers.shape}")
print(f"Food Listings: {food_listings.shape}")
print(f"Claims: {claims.shape}\n")

Providers: (1000, 7)
Receivers: (1000, 6)
Food Listings: (1000, 8)
Claims: (1000, 5)

In [81]:
# SQL Connection Testing
import pandas as pd

query = "SELECT * FROM providers LIMIT 5"
result = pd.read_sql(query, con=engine)
display(result)

,Provider_ID,Name,Type,Address,City,Phone_Extension,Contact_Number
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions, Andreamouth, OK ...",New Jessica,NaN,+16002200480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream, Welchtown, OR 27136",East Sheena,6297,+19252838901
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507, Guzmanchester, W...",Lake Jesusview,NaN,0015172952206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409, Port Jesus, IA 61188",Mendezmouth,401,5569448935
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319, Saraborough, MA 53978",Valentineside,NaN,1937146577

In [1]:
import os

# Define the old name and the correct hidden name
old_name = "Git_file.gitignore"
new_name = ".gitignore"

if os.path.exists(old_name):
    os.rename(old_name, new_name)
    print("✅ Successfully renamed Git_file.gitignore to .gitignore!")
else:
    print("❌ Git_file.gitignore not found. Check if it's already renamed or in another directory.")

✅ Successfully renamed Git_file.gitignore to .gitignore!

In [10]:
gitignore_content = """__pycache__/
*.pyc
.ipynb_checkpoints/
.env
.streamlit/secrets.toml
"""

with open(".gitignore", "w") as f:
    f.write(gitignore_content)
print("✅ .gitignore has been written successfully!")

✅ .gitignore has been written successfully!

In [11]:
with open(".gitignore", "r") as f:
    print(f.read())

__pycache__/
*.pyc
.ipynb_checkpoints/
.env
.streamlit/secrets.toml